module.exports = {
  REQ_ORDER_CREATE: "order_create",
  REQ_ORDER_MODIFY: "order_modify",
  REQ_ORDER_CANCEL: "order_cancel",
  REQ_ORDER_MASS_CANCEL: "order_mass_cancel",
  REQ_ORDER_MASS_STATUS: "order_mass_status",
  REQ_POSITION_MODIFY: "position_modify",
  REQ_POSITION_CLOSEBY: "position_closeby",
  REQ_POSITION_MASS_STATUS: "position_mass_status",
  REQ_ACCOUNT_INFO: "account_info",
  MSG_ORDER_CREATED: "order_created",
  MSG_ORDER_UPDATED: "order_updated",
  MSG_ORDER_DELETED: "order_deleted",
  MSG_ORDER_MASS_STATUS: "order_mass_status",
  MSG_ORDER_CREATE_REJECTED: "order_create_rejected",
  MSG_ORDER_MODIFY_REJECTED: "order_modify_rejected",
  MSG_ORDER_CANCEL_REJECTED: "order_cancel_rejected",
  MSG_POSITION_CREATED: "position_created",
  MSG_POSITION_UPDATED: "position_updated",
  MSG_POSITION_DELETED: "position_deleted",
  MSG_POSITION_MASS_STATUS: "position_mass_status",
  MSG_POSITION_MODIFY_REJECTED: "position_modify_rejected",
  MSG_POSITION_CLOSEBY_REJECTED: "position_closeby_rejected",
  MSG_DEAL_CREATED: "deal_created",
  MSG_ACCOUNT_INFO: "account_info",
  MSG_ACCOUNT_BALANCE_UPDATED: "account_balance_updated",
};
